### ISSUE TITLE
Can't find psalm.xml

### ISSUE THREAD

**Issue by Ciantic** [psalm/psalm-vscode-plugin#1]
I'm testing this plugin, I have installed psalm globally, it works from the command line.

However the extension keeps giving me the "No psalm.xml config..."

![image](https://user-images.githubusercontent.com/64731/47860988-750aba80-ddfa-11e8-8c17-2da624a2f78c.png)

I also tried without workspaces:

![image](https://user-images.githubusercontent.com/64731/47861157-d3d03400-ddfa-11e8-8de0-54c54f3179a9.png)

I have checked your extension.ts and I can't find any problems from my setup. Maybe the isFile is not working correctly somehow.

*Edit* Maybe this is Windows issue?

**Comment by muglug** [comment]
High likelihood of it being a Windows issue - I’ll fire up a machine, likely tonight, for testing

**Comment by itskevinsam** [comment]
experiencing same issue in windows.

**Comment by muglug** [comment]
I was delinquent testing - I identified what was causing this problem ([path](https://github.com/psalm/psalm-vscode-plugin/blob/18cbfc325b6af4f7dabc411056995952d5b2f76d/src/extension.ts#L64) should actually be `fsPath`), but not Windows compatibility in general. Will hopefully have a fix today.

**Comment by muglug** [comment]
Thanks for your extreme patience - the latest version of both Psalm and this plugin (3.0.1 and 0.6.0 respectively) contain fixes for windows. Tested, very slowly, on VS Code running under VirtualBox on a Mac.
