### ISSUE TITLE
Extension stuck on starting

### ISSUE THREAD

**Issue by danog** [psalm/psalm-vscode-plugin#120]
The extension seems to be stuck on startup, with only this in the extension logs:

```
[INFO - 12:45:34 PM] Starting language server
```

No PHP or Psalm process can be found in the process list.

Edit: After disabling TCP mode for the LS, I'm now getting a version error for my custom fork of psalm with tag `4.10.0.11`, would be nice if this extended versioning scheme didn't cause a crash :)

**Comment by tm1000** [comment]
Please post the error as without it I can't be if any help
