### ISSUE TITLE
Is it possible to use a global psalm installation?

### ISSUE THREAD

**Issue by betovidal** [psalm/psalm-vscode-plugin#134]
Hello! I made a global installation of psalm like:

`composer global require vimeo/psalm`

However, I keep getting the error "Psalm is not installed", when I open vscode.

The instructions are pretty clear about installing psalm as a local dependency, inside my project folder, however for other language servers (python-language-server, typescript-language-server) it's possible to have a single global installation for every project. I was wondering if it's currently possible or if I should stick to the locally installed psalm instead.

Also, if there's a different communication channel for questions I'll close this issue and move it there.

**Comment by Pictor13** [comment]
I fixed that with `which psalm` and setting the value into psalm-plugin setting _"Psalm Script Path"_.

**Comment by betovidal** [comment]
Thanks a lot @Pictor13 ! In case another newbie like me stumbles upon this:

`which psalm` will yield something like "/home/user/.config/composer/vendor/bin/psalm", however I needed to link it to "/home/user/.config/composer/vendor/bin/**psalm-language-server**"

And this configuration goes into the user's configuration settings.json:
```
{
    ...
    "psalm.psalmScriptPath": "/home/user/.config/composer/vendor/bin/psalm-language-server"
}
```
