### ISSUE TITLE
Error Logs Automatically Put Themselves In The Foreground

### ISSUE THREAD

**Issue by PythooonUser** [psalm/psalm-vscode-plugin#141]
## Summary
When there is an error with psalm, e.g. the parsing failed of a PHP file, then the logs in the output window get shown automatically.

This happens without any user interaction, and most often at a moment when I'm using the VS Code console. But also when the console view is not expanded, the logs will appear automatically.

## Expectation
I would expect that the logs do not get shown so prominently, but only when I actually click on the "Show Logs" button of the notification pop-up.

## System
- Ubuntu, Windows
- VS Code: 1.63.2
- getpsalm.psalm-vscode-plugin: 2.5.0

**Comment by tm1000** [comment]
Hi there

I have no control over this as a plug-in developer. This is part of vscode itself. You should report the error to Microsoft as there is no where in the code I redirect you to the output console on errors.

**Comment by PythooonUser** [comment]
Hey :wave: 

Yeah, I had a look at `src/LoggingService.ts` and you just forward the logs to VS Code it seems.

Alright, thanks. I just observed this behavior for this extension only so far.

**Comment by tm1000** [comment]
I've also tried to override the message vscode shows you on a crash. It works locally in development but stopped working once deployed. I suspect this is a security feature to protect the integrity of vscode during crashes.
