### ISSUE TITLE
"error" marks appear in strange places

### ISSUE THREAD

**Issue by palansher** [psalm/psalm-vscode-plugin#149]
Hello!

Very useful extension. Yet daily it fu..s my brain :(

There are two most important problems:

1) pls look at the picture
Probably, it is related to cache.
But vendor/bin/psalm --clear-global-cache  does not help.
I also tried to reopen the file and make some changes in types definitions - no luck.

2)
Also, almost every time extension does not get in attention to new code after variable/class renaming. File saving and file reopening do not help. It still "remember" old types.
Most of the time (but not 100%) the VSCode app reload helps.

Thank you for your important efforts!

![image](https://user-images.githubusercontent.com/24850253/151527057-ffaf38ac-8712-4fa7-93b7-3012badf05e7.png)

**Environment:**

Remote SSH workspace on Ubuntu 18.04
VSCode(last) on Windows 10 x64
ext. ver - 2.5.0
vimeo/psalm                           4.19.0
weirdan/doctrine-psalm-plugin         v2.1.0

ext settings:

```
"psalm.unusedVariableDetection": true,
"psalm.maxRestartCount": 10,
"psalm.hideStatusMessageWhenRunning": false,
"psalm.logLevel": "WARN",
```

psalm settings:
```
<?xml version="1.0"?>
<psalm
    totallyTyped="true"
    resolveFromConfigFile="true"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="https://getpsalm.org/schema/config"
    xsi:schemaLocation="https://getpsalm.org/schema/config vendor/vimeo/psalm/config.xsd"
    cacheDirectory="./var/cache/.psalm"
    autoloader="config/bootstrap.php"
>
    <plugins>
        <pluginClass class="Psalm\PhpUnitPlugin\Plugin"/>
        <pluginClass class="Lctrs\PsalmPsrContainerPlugin\Plugin"/>
    <pluginClass class="Weirdan\DoctrinePsalmPlugin\Plugin"/></plugins>

    <projectFiles>
        <directory name="bin"/>
        <directory name="config"/>
        <directory name="include"/>
        <directory name="public"/>
        <directory name="service"/>
        <directory name="src"/>
        <ignoreFiles>
            <directory name="vendor"/>
            <directory name="deleted"/>
            <directory name="test"/>
        </ignoreFiles>
    </projectFiles>

    <issueHandlers>
        <!-- <MixedArrayAccess errorLevel="info" /> -->
        <LessSpecificReturnType errorLevel="info"/>
    </issueHandlers>
</psalm>

```

**Comment by palansher** [comment]
Looks like sporadic messages. It underlines even parts of words.
![image](https://user-images.githubusercontent.com/24850253/151543992-379f7e15-d725-4f2e-b2a1-aa3636c9fd8a.png)

**Comment by palansher** [comment]
The pointless case of  "non-referenced/ non-used variable error"

![image](https://user-images.githubusercontent.com/24850253/151548611-05e198e3-0e92-432c-8a42-4b99c46a817c.png)

**Comment by tm1000** [comment]
This is technically an issue in upstream and nothing this plug-in can do

For more details see: https://github.com/psalm/psalm-vscode-plugin/issues/143

I plan to work on it in my free time but you should post this but report over there
