### ISSUE TITLE
Hide warnings

### ISSUE THREAD

**Issue by binarious** [psalm/psalm-vscode-plugin#16]
I'm using psalm with `errorLevel` 2. This results in errors from level 1 to be shown with yellow warnings. Is there a way to hide these?

**Comment by tm1000** [comment]
@binarious So to do this it has to be initiated on the server, we could do this a few different ways

1. Add a flag to the server `--disable-info`, allowing one to turn it off in VSCode settings
2. Add config option to Psalm.xml (probably not a good idea)
3. Utilize a psalm.rc file (this would probably be confusing)

Will probably need to go with option 1

**Comment by tm1000** [comment]
see: https://github.com/tm1000/psalm/tree/feature/upgrade-lsp
