### ISSUE TITLE
Ignores `php.executablePath` VSCode configuration

### ISSUE THREAD

**Issue by huchim** [psalm/psalm-vscode-plugin#17]
Hello!

I'm receiving this message from extension `v1.2.2`:
> PHP executable not found. Install PHP 7 and add it to your PATH or set the php.executablePath setting

I created a new entry in my `settings.json` file with `php.executablePath` but VSCode say "unknown configuration Setting".

Add PHP directory to `$PATH` works fine but not using VsCode configuration.

```json
{
    "php.executablePath": "C:\\home\\etc\\php\\php.exe",
    "php.validate.executablePath": "C:\\home\\etc\\php\\php.exe",
    "php.validate.enable": false
}
```

```
Version: 1.47.3 (user setup)
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T13:12:49.994Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```

```bash
$ php -v
PHP 7.2.31 (cli) (built: May 12 2020 10:49:38) ( NTS MSVC15 (Visual C++ 2017) x86 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
```

Thanks!

**Comment by pristinesource** [comment]
@huchim You will want to use the following config options for Psalm:
```
{
    "psalm.phpExecutablePath": "C:\\home\\etc\\php\\php.exe",
    "psalm.phpExecutableArgs": [
        "-dxdebug.remote_autostart=0",
        "-dxdebug.remote_enable=0",
        "-dxdebug_profiler_enable=0"
    ],
    "psalm.connectToServerWithTcp": true
}
```

The other settings you have there are for the built in PHP syntax and validation in VSCode.  You will still need to have the values as you have set there, although it may be beneficial to have `php.validate.enable` set to `true` unless you are using a different PHP validator such as "PHP IntelliSense" (https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-intellisense) or "PHP Intelephense" (https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client).

**Comment by pristinesource** [comment]
@huchim Indeed the error message you got is correct because it says the wrong config key, and I will make a bug report for it so it can be fixed during the next release.  Thank you for letting us know! 😉
