### ISSUE TITLE
Report from VS code

### ISSUE THREAD

**Issue by siberry** [psalm/psalm-vscode-plugin#189]
Issue Type: <b>Bug</b>

# Behaviour

## Expected

XXX

## Actual

XXX

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1.

# Diagnostic data

-   PHP version: PHP 7.4.30 (cli) (built: Jun  9 2022 09:20:03) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.30, Copyright (c), by Zend Technologies

-   Psalm version: unknown

<details>

<summary>"Psalm Language Server" channel in the OUTPUT panel (Last 1000 lines)</summary>

<p>

```
[INFO  - 5:03:18 PM] Starting language server
[WARN  - 5:03:20 PM] Psalm Version could not be parsed as a Semantic Version. Got "Psalm dev-master@667dcc2e49e241fdff00368bfcfffc987bf62e9d
". Assuming unknown
[Info  - 5:03:29 PM] Connection to server got closed. Server will restart.
[WARN  - 5:03:29 PM] Psalm Version could not be parsed as a Semantic Version. Got "Psalm dev-master@667dcc2e49e241fdff00368bfcfffc987bf62e9d
". Assuming unknown
[Info  - 5:03:38 PM] Connection to server got closed. Server will restart.
[WARN  - 5:03:38 PM] Psalm Version could not be parsed as a Semantic Version. Got "Psalm dev-master@667dcc2e49e241fdff00368bfcfffc987bf62e9d
". Assuming unknown
[Info  - 5:04:01 PM] Connection to server got closed. Server will restart.
[WARN  - 5:04:02 PM] Psalm Version could not be parsed as a Semantic Version. Got "Psalm dev-master@667dcc2e49e241fdff00368bfcfffc987bf62e9d
". Assuming unknown
[Info  - 5:04:35 PM] Connection to server got closed. Server will restart.
[WARN  - 5:04:35 PM] Psalm Version could not be parsed as a Semantic Version. Got "Psalm dev-master@667dcc2e49e241fdff00368bfcfffc987bf62e9d
". Assuming unknown
[Error - 5:05:16 PM] Connection to server got closed. Server will not be restarted.
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```
phpExecutablePath: "/opt/homebrew/bin/php"
phpExecutableArgs: ["-dxdebug.remote_autostart=0","-dxdebug.remote_enable=0","-dxdebug_profiler_enable=0"]
psalmVersion: null
psalmScriptPath: "vendor/vimeo/psalm/psalm-language-server"
psalmScriptArgs: []
disableAutoComplete: false
maxRestartCount: 5
unusedVariableDetection: false
enableVerbose: false
connectToServerWithTcp: false
enableUseIniDefaults: false
logLevel: "INFO"
analyzedFileExtensions: [{"scheme":"file","language":"php"},{"scheme":"untitled","language":"php"}]
configPaths: ["psalm.xml","psalm.xml.dist"]
hideStatusMessageWhenRunning: true
```

</p>
</details>

Extension version: 2.7.0
VS Code version: Code 1.69.2 (Universal) (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T16:12:57.074Z)
OS version: Darwin arm64 21.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|58, 40, 156|
|Memory (System)|32.00GB (1.40GB free)|
|Process Argv|. --crash-reporter-id 03b008ee-508f-44d9-9223-7fa862ba8397|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30525689
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912cf:30529770
vsclangdf:30486550
c4g48928:30535728

```

</details>

**Comment by tm1000** [comment]
The error is the psalm version could not be determined because you are using it from a development branch. This isn't a bug
