### ISSUE TITLE
Extension linting does not update in VSCode

### ISSUE THREAD

**Issue by nmsmith22389** [psalm/psalm-vscode-plugin#21]
In my project when the Psalm language server starts running it will underline linting errors. But then those linting errors do not update when the page code shifts.

I checked the Dev Tools and the language server does not crash and is still running. But one weird thing I noticed was that when the language server is started it is started with `--use-extended-diagnostic-codes` and `--verbose` despite debugging in the extension settings being turned off.

I have an older project running Psalm@v3.10.1 instead of the newest version and the extension updates like normal and doesn't launch the language server with those flags on.

Can anyone help?

**Comment by nmsmith22389** [comment]
It seems to break in `vimeo/psalm@v3.16.0`... `v3.15.0` seems to work fine.

**Comment by 9brada6** [comment]
> It seems to break in vimeo/psalm@v3.16.0... v3.15.0 seems to work fine.

Can also confirm thinks, thanks for the info to which version to use.

**Comment by muglug** [comment]
This was broken by https://github.com/vimeo/psalm/commit/1d13d282229e9dc82bae894f330ba0432f50d0c8 cc @orklah – not sure what in there caused it

**Comment by orklah** [comment]
My best guess would be a method that declare returning a string and actually return an object with __toString. If the actual object is expected by someone, it would break. I would have expected Psalm to pickup on that however...

I'm trying to look

**Comment by muglug** [comment]
Don't bother, it's literally the dumbest thing: https://github.com/vimeo/psalm/commit/32787169d7e3c2bbd8a33e1d1351cf24bb017836

**Comment by muglug** [comment]
Something is reading docblocks explicitly 🙃

**Comment by muglug** [comment]
Specifically this: https://github.com/felixfbecker/php-advanced-json-rpc/blob/7eae8181bffe0e04df51682171e56e2bba533161/lib/Dispatcher.php

**Comment by orklah** [comment]
:o

Impressive, I could have searched for a while!

How did you find the issue?

**Comment by muglug** [comment]
trial and error, removing changes from the diff

**Comment by orklah** [comment]
ouch, that hurts :( 

Sorry for that

**Comment by muglug** [comment]
You weren't to know (neither was I)!

Psalm 3.18 has the fix, closing this.
