### ISSUE TITLE
How does this plugin work with the baseline file?

### ISSUE THREAD

**Issue by xdhmoore** [psalm/psalm-vscode-plugin#22]
I have created a baseline file using the psalm cli, but the vs code plugin doesn't seem to be using it. It just displays all the errors, even those I want it to ignore. It does seem to be picking up my psalm.txt file ok though. I looked for an '--ignore-baseline' argument in the plugin code but I didn't see anything. Maybe the language server doesn't respect the baseline file?

**Comment by tm1000** [comment]
The language server is sent psalm.xml not psalm.txt. Maybe you mistyped this in this issue?

**Comment by xdhmoore** [comment]
I probably meant psalm.xml, but I no longer work for that organization, so I can't reproduce it at this point.

**Comment by tm1000** [comment]
All good. Thanks for the update!
