### ISSUE TITLE
Exception when running psalm language server

### ISSUE THREAD

**Issue by purplep2** [psalm/psalm-vscode-plugin#24]
Hi, I'm trying to run Psalm analysis on WordPress in VS Code.
However, I encountered an exception thrown, causing Psalm to crash:
Uncaught InvalidArgumentException: Could not get class storage for domdocumentfragment in /vendor/vimeo/psalm/src/Psalm/Internal/Provider/ClassLikeStorageProvider.php:42

**Comment by tm1000** [comment]
I've been unable to replicate this on newer versions of Psalm (4.9.x)
