### ISSUE TITLE
Very slow on large files

### ISSUE THREAD

**Issue by M393** [psalm/psalm-vscode-plugin#251]
When editing a large file with a few thousand lines the plugin is very slow. It can take multiple minutes until the the errors for the current document state are shown. 
During this lots of messages as below are logged:
> [Error - 4:54:36 PM] Method $/cancelRequest is not implemented
[Error - 4:54:36 PM] Method $/cancelRequest is not implemented
[Error - 4:54:40 PM] Method $/cancelRequest is not implemented
[Error - 4:54:40 PM] Method $/cancelRequest is not implemented
[Error - 4:54:44 PM] Method $/cancelRequest is not implemented
[Error - 4:54:44 PM] Method $/cancelRequest is not implemented
[Error - 4:54:44 PM] Method $/cancelRequest is not implemented
[Error - 4:54:44 PM] Method $/cancelRequest is not implemented
[Error - 4:54:44 PM] Method $/cancelRequest is not implemented
[Error - 4:54:45 PM] Method $/cancelRequest is not implemented
[Error - 4:54:45 PM] Method $/cancelRequest is not implemented
[Error - 4:54:45 PM] Method $/cancelRequest is not implemented
[...]

So I assume the plugin queues every change of the document to be sent to the psalm language server, without ever skipping outdated states.

Would be great if this could be improved.
This plugin is very helpful otherwise, thanks.

**Comment by tm1000** [comment]
It's more so that every change is processed and there is no way to cancel that because php's non-async nature

You can try messing with the setting: `--on-change-debounce-ms=`

In my company we use:

```
	"psalm.psalmScriptArgs": [
		"--on-change-debounce-ms=500"
	],
```

**Comment by M393** [comment]
Thanks for this, it is much better.
