### ISSUE TITLE
Errors when viewing commit diff

### ISSUE THREAD

**Issue by zdmitchell** [psalm/psalm-vscode-plugin#26]
In VS Code, I often like to look at a commit diff. Every time I open a commit diff for a PHP file, the output window pops up with Psalm errors.

The error code is `32603`, with message: `Message: InvalidArgumentException: Not a valid file URI`. It then gives the file name, which is something like: `git:ABSOLUTE_FILE_PATH?%7B%22path%22:%22ABSOLUTE_FILE_PATH%22,%22ref%22:%22COMMIT_HASH%22%7D`.

Obviously, we don't what to run Psalm on a "diff" file, so maybe we should check explicitly for this case?

**Comment by tm1000** [comment]
Help me to duplicate this. I'm right clicking on a file in my project then clicking "Commit Changes" then clicking "Open Changes with previous revision" and this is not triggering any event from VSCode to the Language server so I can't seem to replicate it

**Comment by zdmitchell** [comment]
Weird. I'll close this while I look into coming up with some repro steps. Maybe it's something with my environment.
