### ISSUE TITLE
Psalm crashes while it's installed  under WSL

### ISSUE THREAD

**Issue by widoz** [psalm/psalm-vscode-plugin#283]
It has been already some days since everytime I open a folder in VSCode I obtain the following message

> The Psalm Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.

Even closing all projects, waiting 10 minutes I obtain the same message. 

Honestly I don't know where to start to try to understand the problem :/

**Comment by tm1000** [comment]
Please post the output from the output tab of Visual Studio Code.

**Comment by widoz** [comment]
Hi there, sorry it was my fault, looks like that due to docker the `.psalm` directory of the project was set to `root:root` and this caused issues to PSALM because the `cache` is specified within that directory.
