### ISSUE TITLE
code check is not being executed on save

### ISSUE THREAD

**Issue by danielzzz** [psalm/psalm-vscode-plugin#284]
hello, for some reason I cannot get the extension to check the file on save.

the only time it does it is when I execute the "analyze workspace" command.

What might be the problem here?

thanks in advance,
dan

**Comment by tm1000** [comment]
You need to look in the output window.

**Comment by jkrauss82** [comment]
I have installed psalm in VS Code but it seems to do nothing at all in a pslam project I am working on (`psalm.xml` and `psalm-baseline.xml` are in the root of the project).

I do not see an option to run it manually in VS Code and it is not running on saving files either (nothing is printed to the output tab).

I also haven't found any meaningful links when doing a web search for this problem.

If someone could point me in the right direction I would highly appreciate it.

VS Code:
Version: 1.90.0
Commit: 89de5a8d4d6205e5b11647eb6a74844ca23d2573
Date: 2024-06-04T19:43:07.605Z
Electron: 29.4.0
ElectronBuildId: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Linux x64 6.5.0-44-generic

Psalm Plugin:
v2.7.0
Published 2018-10-23, 22:38:47
Last released 2022-07-26, 00:56:10
Last updated 2024-08-26, 11:24:08
Identifier getpsalm.psalm-vscode-plugin

**Comment by tm1000** [comment]
If nothing is printed in the output tab then it's not setup properly. 

Please open a new issue for this
