### ISSUE TITLE
Issue class (optionally) in the error description

### ISSUE THREAD

**Issue by rzvc** [psalm/psalm-vscode-plugin#287]
Would be nice to have the ability to add the issue type to the error description.

As it is, if I want to suppress a particular error, I have to run psalm externally in order to obtain the class of issue that I want to suppress.

For example, instead of just "Unable to determine the type that $x is being assigned to", it could say "[MixedAssignment] Unable to determine the type that $x is being assigned to".

Is this already possible to do?

**Comment by tm1000** [comment]
If you use quick fixes it'll add the suppression automatically. You can also click the number link in the hover and it'll send you to the corresponding page.

**Comment by weirdan** [comment]
@tm1000 would you be opposed to including the issue type in the message itself though? This could be a simple server-side fix, and all clients would benefit from it. I, for one, would love to see it in nvim as well, e.g.:
![image](https://github.com/psalm/psalm-vscode-plugin/assets/57403/11739d49-23ea-44b5-ac3e-dbd6f7e0b4ce)

**Comment by tm1000** [comment]
I don't mind 😀
