### ISSUE TITLE
Nothing happening, no linting, no errors.

### ISSUE THREAD

**Issue by newlinkcapital** [psalm/psalm-vscode-plugin#3]
Hi, I installed the plugin, then I installed psalm using composer and I created a psalm.xml file that looks like this.

`<?xml version="1.0"?>
<psalm>
    <projectFiles>
        <directory name="app" />
    </projectFiles>
</psalm>`

I dont see any linting going on in my project. should this configuration suffice?

**Comment by adammarton** [comment]
Can confirm, all I can see in the debug log is:

```
Extension Host console.ts:134
[Extension Host] starting Psalm Language Server php 
Array(2)
  0: "<project-dir>\vendor\bin\psalm-language-server"
  1: "--tcp=127.0.0.1:58911"
```

No errors, no nothing. Windows, latest VSCode/Psalm.

**Comment by AdamMarton** [comment]
More context:

Without actually requiring Psalm in the given folder/project in VSCode, you have to set `psalm.psalmScriptPath` to point your global `vendor\bin` path, otherwise you'll get the following error:

```
The setting psalm.psalmScriptPath refers to a path that does not exist. path: ' + psalmScriptPath
```

where `psalmScriptPath` is the currently opened folder + `\vendor\bin\psalm-language-server`.

Enabling debug just displays this:

```
out: 
dir=$(cd "${0%[/\\]*}" > /dev/null; cd "../vimeo/psalm" && pwd)

if [ -d /proc/cygdrive ]; then
    case $(which php) in
        $(readlink -n /proc/cygdrive)/*)
            # We are in Cygwin using Windows php, so the path must be translated
            dir=$(cygpath -m "$dir");
            ;;
    esac
fi

"${dir}/psalm-language-server" "$@"
```

Can we get some update on how to configure this?

**Comment by iluuu1994** [comment]
It doesn't work for me either. All I get is these:

```
[Info  - 9:04:22 PM] Connection to server got closed. Server will restart.
[Info  - 9:04:22 PM] Connection to server got closed. Server will restart.
[Info  - 9:04:23 PM] Connection to server got closed. Server will restart.
[Info  - 9:04:24 PM] Connection to server got closed. Server will restart.
[Error - 9:04:25 PM] Connection to server got closed. Server will not be restarted.
```

@muglug Can I provide you any logs that could be useful?

**Comment by muglug** [comment]
@AdamMarton ah, it's sort of assumed that Psalm is also installed in your project, but I should include it in the instructions

**Comment by muglug** [comment]
@iluuu1994 are you on Mac or Windows?

**Comment by AdamMarton** [comment]
> @AdamMarton ah, it's sort of assumed that Psalm is also installed in your project, but I should include it in the instructions

I've also tried that as well. That still not helps.

**Comment by iluuu1994** [comment]
I'm on macOS.

**Comment by iluuu1994** [comment]
Suddenly works, please don't ask me why 🤷‍♂ I changed nothing.

**Comment by AdamMarton** [comment]
Unfortunately I cannot say the same :/

**Comment by ADmad** [comment]
@AdamMarton As pointed out [here](https://github.com/psalm/psalm-vscode-plugin/issues/2#issuecomment-502188774) the `psalmScriptPath` setting needs to point to a php file not the executable under `bin`. The help text is misleading.

**Comment by AdamMarton** [comment]
> @AdamMarton As pointed out [here](https://github.com/psalm/psalm-vscode-plugin/issues/2#issuecomment-502188774) the `psalmScriptPath` setting needs to point to a php file not the executable under `bin`. The help text is misleading.

I've already tried this. Psalm bails out when I'm using that executable:
![image](https://user-images.githubusercontent.com/5418343/61053253-82e2f780-a3ed-11e9-816d-ecd81d2e25d4.png)

**Comment by ADmad** [comment]
>  Psalm bails out when I'm using that executable

You are **not** supposed to use an executable.

**Comment by AdamMarton** [comment]
> @AdamMarton As pointed out [here](https://github.com/psalm/psalm-vscode-plugin/issues/2#issuecomment-502188774) the `psalmScriptPath` setting needs to point to a php file not the executable under `bin`. The help text is misleading.

Thanks, @ADmad I've re-read the linked comment and you were right. Now at least I have errors everywhere in the devtools.

**Comment by muglug** [comment]
@ADmad @AdamMarton would you be able to PR to improve the language? I don't know how best to communicate to Windows users.

**Comment by ADmad** [comment]
@muglug I don't think the issue has much to do with Windows (nor am I personally interested in Windows, I use Linux). 

As I commented [here](https://github.com/psalm/psalm-vscode-plugin/issues/2#issuecomment-510473240) I want this VSCode plugin to use the language server available through the psalm.phar. I don't think that's currently possible.

**Comment by muglug** [comment]
> I want this VSCode plugin to use the language server available through the psalm.phar

`path/to/psalm.phar --languague-server` should work

**Comment by muglug** [comment]
> I want this VSCode plugin to use the language server available through the psalm.phar

`path/to/psalm.phar --language-server` should work

**Comment by ADmad** [comment]
It doesn't, VSCode throws error. I'll provide a screenshot once I get to a PC.

**Comment by ADmad** [comment]
This is the error I get trying what you suggest:

![Screenshot from 2019-07-11 23-28-40](https://user-images.githubusercontent.com/142658/61074018-58685d00-a434-11e9-8246-2e91f1147199.png)

Config set as `"psalm.psalmScriptPath": "../../../../home/admad/bin/psalm.phar --language-server"`. (Also it treats all paths as relative hence the preceding `../`s).

**Comment by beaucollins** [comment]
I was able to get things up and running with the changes proposed in #7.

**Comment by muglug** [comment]
Going to close this, absent any new info
