### ISSUE TITLE
Provide plugin on open-vsx.org

### ISSUE THREAD

**Issue by camlafit** [psalm/psalm-vscode-plugin#31]
Hello

Could be possible to provide plugin on open-vsx.org market place ? Could be useful to use it with vscode fork as vscodium.
More information about this :
https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions-marketplace

Thanks a lot

**Comment by thomasbley** [comment]
This is very useful for forks of vs-code (e.g. Eclipse Theia, code-server https://github.com/cdr/code-server), which are not allowed to use VS-Code marketplace.

Quoting from https://github.com/cdr/code-server/blob/v3.8.0/doc/FAQ.md#differences-compared-to-vs-code
```
While the core of VS Code is open source, the marketplace and many published Microsoft extensions are not.
Furthermore, Microsoft prohibits the use of any non-Microsoft VS Code from accessing their marketplace.
See the TOS.
Marketplace Offerings are intended for use only with Visual Studio Products and Services and you may only install and use Marketplace Offerings with Visual Studio Products and Services.
As a result, we cannot offer any extensions on the Microsoft marketplace. Instead, we have created our own marketplace for open source extensions. It works by scraping GitHub for VS Code extensions and building them. It's not perfect but getting better by the day with more and more extensions.
```
Also: https://github.com/cdr/code-server/blob/v3.8.0/doc/FAQ.md#how-do-i-configure-the-marketplace-url

So having psalm-vscode-plugin available on open-vsx.org would be great!

**Comment by tm1000** [comment]
I'll look into this once I get the extension republished on the Microsoft marketplace

**Comment by tm1000** [comment]
So I tried signing up on eclipse and it basically blocked me. The email to register takes 24 hours to get into my inbox. By the time I click the link it tells me my account is invalid. 

I'll try a few more times but so far it seems like the eclipse servers are overloaded

**Comment by tm1000** [comment]
All done! https://open-vsx.org/extension/getpsalm/psalm-vscode-plugin

**Comment by camlafit** [comment]
Hello

Perfect. It's now installed :)
Thank a lot
