### ISSUE TITLE
Update cache on composer.json change

### ISSUE THREAD

**Issue by jonorozcoc** [psalm/psalm-vscode-plugin#32]
The plugin works correctly until I install a new package and use any code from the package saying the object doesn't exists

Could be possible to reload files when composer.json changes?

**Comment by tm1000** [comment]
Ideally this would have to run *after* you've updated composer.json and run composer update. Looks like we need to hook into `workspace/didChangeWatchedFiles` for this to work (which should re-analyze)

**Comment by tm1000** [comment]
Requires https://github.com/vimeo/psalm/pull/6014
