### ISSUE TITLE
Autocomplete for PHPUnit 9.x

### ISSUE THREAD

**Issue by thomasbley** [psalm/psalm-vscode-plugin#34]
I'm using psalm-vscode-plugin v1.2.2 with vs-code 1.52.1 (and code-server 3.8.1) and tried to get auto-complete working for phpunit 9.x (loaded as composer library). E.g. assertTrue() cannot be autocompleted from PHPUnit\Framework\TestCase -> PHPUnit\Framework\Assert.
When I type assertTrue manually, detecting invalid parameters works.

![Screenshot_20210206_200602](https://user-images.githubusercontent.com/941223/107127636-b6cb1b00-68b7-11eb-86d5-db5a6e398fae.png)
![Screenshot_20210206_201026](https://user-images.githubusercontent.com/941223/107127639-bd599280-68b7-11eb-9d46-1fdb24eb79e2.png)

**Comment by thomasbley** [comment]
happens with psalm 4.4.1 and psalm 4.5.1

**Comment by muglug** [comment]
Ah this is actually a but with the language server, closing in favour of https://github.com/psalm/psalm-vscode-plugin/issues/34

**Comment by muglug** [comment]
Sorry, meant https://github.com/vimeo/psalm/issues/5295
