### ISSUE TITLE
Project maintainer or collaborator

### ISSUE THREAD

**Issue by jonorozcoc** [psalm/psalm-vscode-plugin#35]
Hi,

First at all, this is an awesome VSCode extension and Psalm it's a good tool.

I use it on many of my projects and I want to improve it in order to make a better experience using the extension. I would like to contribute to the project as maintainer or collaborator in order to move faster to marketplace

I hope to work on this project!

**Comment by tm1000** [comment]
Hi there! I'm maintaining it now but if you want to be a co-maintainer just reach out to @mattbrowndev on twitter!
