### ISSUE TITLE
is this project dead?

### ISSUE THREAD

**Issue by tm1000** [psalm/psalm-vscode-plugin#42]
Serious question. Psalm itself is alive. But the last release of this plugin was 4/22/2020, since then there's been numerous PRs merged but no releases. Is there a release manager? or someone in charge of building this and putting it into the Marketplace?

@pristinesource @muglug

**Comment by muglug** [comment]
Not dead, but definitely dormant. If you want to become a maintainer LMK!

**Comment by tm1000** [comment]
@muglug I'd love to be a maintainer! You can check my github page to see that I regularly contribute to open source projects here on github. I used to work for Sangoma (Maintainers of FreePBX) as the lead engineer/director as well.

As far as giving contributor rights here would I also need contributor on the Marketplace?

**Comment by tm1000** [comment]
@muglug Hey Matthew, Let me know how to reach out to you. I followed you on twitter (@tm1000) if you wanna discuss anything in private

**Comment by tm1000** [comment]
@muglug My work associate @GameGamer43 would like to co-maintain this with me as well. The more people the better!

**Comment by muglug** [comment]
I've added you both!
