### ISSUE TITLE
No psalm.xml config found in project root

### ISSUE THREAD

**Issue by Horttcore** [psalm/psalm-vscode-plugin#5]
That is true, but I got a psalm.xml config in a subfolder. Maybe the plugin could search for any psalm config in the project and run that folder against it?

**Comment by mriccid** [comment]
I'm running into the same problem. It would be great if the plugin was able to find psalm.xml in ancestor folders or allow for the path to be configured for a workspace.

**Comment by Horttcore** [comment]
Any Feedback would be nice, or is it dead?

**Comment by muglug** [comment]
Not quite dead - though maintaining this plugin is not a huge priority for me (most of my open-source time is instead dedicated to `vimeo/psalm`). If you know Javascript I encourage you to update the plugin to do that searching, and submit a PR – I'll gladly accept.

**Comment by pristinesource** [comment]
@Horttcore, it looks like there is a now configuration option for this extension called `psalm.configPaths` that allows you to specify the path to your config file.  Also, VSCode allows for setting any configuration values for extensions per workspace, so you should be able to set the `psalm.configPaths` for each workspace to your desired value.

Does this achieve what you need?  If so, I will close this ticket, but if not, please let me know what is missing.

**Comment by sanmai-NL** [comment]
@Horttcore: could you respond to the previous message, please?

**Comment by muglug** [comment]
Closing this in the meantime
