### ISSUE TITLE
Support for absolute paths for Psalm Client Script Path and Psalm Script Path

### ISSUE THREAD

**Issue by thomasbley** [psalm/psalm-vscode-plugin#71]
Workspace relative paths are working (e.g. bin/psalm_4910.phar),
but absolute paths (e.g. /home/foobar/bin/psalm_4910.phar) give the error message "Psalm is not installed".

I guess this line might get a fallback for absolute paths:
https://github.com/psalm/psalm-vscode-plugin/blob/b5100e21d43f8724a45a083fe588c7223725233c/src/LanguageServer.ts#L601

I suggest to rename "Psalm Client Script Path" to e.g. "Psalm executable (workspace relative path + filename)" or support absolute paths.
I suggest to rename "Psalm Client Script Path" to e.g. "Psalm language server executable (workspace relative Path + filename)" or support absolute paths for the configs.

Tested with:
php 8.0.9
psalm 4.9.1 (phar)
vscode 1.58.2
vscode extension v2.0.5

**Comment by tm1000** [comment]
I think we should support absolute paths it just didnt appear to be working the way you have it working according to #33

**Comment by tm1000** [comment]
As you are the author of #33. Ok I will get to making this work with absolute paths It's not too hard to figure out (slash on front or not would be the difference)

**Comment by tm1000** [comment]
Fixed in 2.1.0
