### ISSUE TITLE
Set vscode minimum version to 1.57.1

### ISSUE THREAD

**Issue by thomasbley** [psalm/psalm-vscode-plugin#77]
Currently package.json defines: "vscode": "^1.58.1", "@types/vscode": "^1.58.1",

Unfortunately, forks of vscode are not always up-to-date with the latest version of vscode. E.g. code-server is currently 1.57.1 which makes the extension fail on install (https://github.com/cdr/code-server/releases). Changing the version in package.json and recompiling makes the installation successful.

Therefore, I'm suggesting to set the minimum vscode version to 1.57.1.

**Comment by tm1000** [comment]
Hi there!

Yeah I jumped the gun a little bit because of dependencybot. I'll have it ignore that moving forward and jump back a few versions of vscode as there's nothing I'm using from the new stuff

**Comment by tm1000** [comment]
Fixed in https://github.com/psalm/psalm-vscode-plugin/releases/tag/2.0.6
