### ISSUE TITLE
No parameters hints after installing

### ISSUE THREAD

**Issue by WossomGonzo** [psalm/psalm-vscode-plugin#81]
When I use vscode without the plugin installed, I can issue <code>ctrl</code>-<code>shift</code>-<code>space</code> to trigger the parameter hint popup and it works.

But after I install the plugin this key sequence doesn't work any more.

Version: 1.59.0
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:13:20.182Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Linux x64 5.11.0-31-generic

PSalm plugin version: v2.1.0

**Comment by tm1000** [comment]
Hi there. 

The parameter hint pop up is embedded deep into vscode. This plug-in isn't able to disable that by any means. You may have other conflicts or issues going on.

**Comment by tm1000** [comment]
So I have both https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client installed and this plugin and I am still able to see parameter hints. If I disable intelephense then I don't see them at all. Since this plugin just interfaces with https://github.com/vimeo/psalm the error appears to be within https://github.com/vimeo/psalm

The returned responses for me look like this (which according to the spec is correct):
```
{
   "result":{
      "signatures":[
         {
            "label":"authorize(mixed $root, array<array-key, mixed> $args, mixed $ctx, GraphQL\\Type\\Definition\\ResolveInfo|null $resolveInfo, Closure|null $getSelectFields)",
            "documentation":null,
            "parameters":[
               {
                  "label":[
                     10,
                     21
                  ],
                  "documentation":null
               },
               {
                  "label":[
                     23,
                     52
                  ],
                  "documentation":null
               },
               {
                  "label":[
                     54,
                     64
                  ],
                  "documentation":null
               },
               {
                  "label":[
                     66,
                     119
                  ],
                  "documentation":null
               },
               {
                  "label":[
                     121,
                     150
                  ],
                  "documentation":null
               }
            ]
         }
      ],
      "activeSignature":0,
      "activeParameter":0
   },
   "id":22,
   "jsonrpc":"2.0"
}
```

**Comment by WossomGonzo** [comment]
Sorry Andrew, I think I am not following you :-(

However I have narrowed down the issue. You were right, the key combination shows the parameters hint _except_ when a class have the magic method `__invoke()`.

Foe example, in the following code if I have the psalm plugin disabled and I position the cursor in the `$plusOne()`, it shows the correct parameter hint if I press the combination keys. But it won't appear once I re-enable the psalm plugin:
```
<?php

class PlusOne
{
    public function __invoke(int $number): int
    {
        return $number + 1;
    }
}

$plusOne = new PlusOne();

echo $plusOne(9);
```

**Comment by tm1000** [comment]
You'll need to report this in the main repository. I will attempt to look into this but I'm closing this issue because it technically has nothing to do with this project and instead is an issue on the main project
