### ISSUE TITLE
reports errors for files outside of projectFiles directory

### ISSUE THREAD

**Issue by kale1d0code** [psalm/psalm-vscode-plugin#9]
From my understanding the plugin should only run against files or directories stated within the projectFiles tag in the config but psalm is reporting problems for files outside of this directory.

I have also tried putting @psalm-suppress in a docblock without an error type at the top of a file I don't want psalm to process.
This works until I save a change within a file.

**Comment by d-damien** [comment]
Use case : wordpress plugin creation.

Put psalm.xml in wordpress root, add "wp-content/plugins/your-plugin" as a project dir. Sometimes you need to open a wp core file to understand its inner working. Psalm plugin will also show errors for this file − and they won't disappear from the console even after closing the file.

It's a minor disturbance though. Overall I've found Psalm to be a lot easier to setup than its counterparts. Thanks for the awesome work, muglug.

**Comment by tm1000** [comment]
Do you not want to see these errors at all?

(Note the errors actually come from the main project, not this project, though the implementation is wrong as its just spitting out an unparsable error: https://github.com/vimeo/psalm/blob/9e9413da6d490c630b0a997f40fdd938cfe10c65/src/Psalm/Internal/LanguageServer/Server/TextDocument.php#L64)

**Comment by tm1000** [comment]
Merged into master (likely 4.18.0)
